### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by VaxisXC** [imthenachoman/imthenachoman.github.io#1]
Hello,

I apologize for reaching out like this, I just had a quick question. I recently came across your [stackoverflow post](https://stackoverflow.com/questions/54424275/undelete-gmail-e-mails-by-when-they-were-deleted-and-or-sort-trash-by-when-an-em) about tagging deleted emails in gmail and was wondering if you could potentially share the full script you use and how to get it set up. It's probably easier than I think but I'm very new to all of this stuff and I'm trying to learn on my own and that script sounds really helpful. I appreciate your time

**Comment by imthenachoman** [comment]
Hey!

No issues for reaching out.  Happy to help.

I will have to dig the script out. Over the years, the script has become a combination of multiple smaller scripts. Give me some time.

The biggest issue with my approach is you end up with A LOT of labels.

**Comment by imthenachoman** [comment]
Hello.

So I don't use this code anymore but here it is. The idea is to create some day/month/hour labels and then apply them to trashed emails on a schedule.

I stopped using this because all the labels were cluttering my inbox. But it did work well enough.

You might have to tweak this code a bit.

```
var mainTrashLabel = "trashed_timestamps";
var trashedEmailsThatAreNotTaggedQuery = 'in:trash -label:' + mainTrashLabel + ' -subject:"dmgs: "';

/ add date/time stamp to emails in trash
function tagTrashedEmailsWithTimestamp()
{
  // find all emails that are not tagged
  
  var trashedEmailsThatAreNotTagged = GmailApp.search(trashedEmailsThatAreNotTaggedQuery);
  
  // only if we have emails that need to be processed
  if(trashedEmailsThatAreNotTagged.length)
  {
    var now = Utilities.formatDate(new Date(), "EST", "MM dd HH").split(" ");
    
    // apply month, day, and hour labels
    GmailApp.getUserLabelByName(mainTrashLabel + "/month-" + now[0]).addToThreads(trashedEmailsThatAreNotTagged);
    GmailApp.getUserLabelByName(mainTrashLabel + "/day-" + now[1]).addToThreads(trashedEmailsThatAreNotTagged);
    GmailApp.getUserLabelByName(mainTrashLabel + "/hour-" + now[2]).addToThreads(trashedEmailsThatAreNotTagged);

    // add the main label so we can search on it later
    GmailApp.getUserLabelByName(mainTrashLabel).addToThreads(trashedEmailsThatAreNotTagged);
  }
  
  //MailApp.sendEmail("imthenachoman@gmail.com", "dmgs: tagged " + trashedEmailsThatAreNotTagged.length + " trashed e-mails", "tagged " + trashedEmailsThatAreNotTagged.length + " trashed e-mails")
}

function init()
{
  mainTrashLabel = "dingo"
  // create the main label
  GmailApp.createLabel(mainTrashLabel);
  
  // create the month labels
  for(var i = 1; i <= 12; ++i)
  {
    GmailApp.createLabel(mainTrashLabel + "/month-" + ("00" + i).slice(-2));
  }
  
  // create the day labels
  for(var i = 1; i <= 31; ++i)
  {
    GmailApp.createLabel(mainTrashLabel + "/day-" + ("00" + i).slice(-2));
  }
  
  // create the hour labels
  for(var i = 0; i <= 23; ++i)
  {
    GmailApp.createLabel(mainTrashLabel + "/hour-" + ("00" + i).slice(-2));
  }
  
}
```
